- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - htop
        - mc
        - tmux
        - vim
