- hosts: localhost
  pre_tasks:
  - name: update repositories
    apt: update_cache=yes
    changed_when: False
    become: true
  
  tasks:
    - include: tasks/packages.yml
    - include: tasks/user.yml
    - include: tasks/tmux.yml
    - include: tasks/asdf.yml
    - include: tasks/zsh.yml
    - include: tasks/fzf.yml
    - include: tasks/jetbrains.yml
    - include: tasks/cargo-packages.yml
    - include: tasks/pip-packages.yml