- name: Copy asdf-rust plugin config
  ansible.builtin.copy:
    src: files/default-cargo-crates
    dest: /home/asim/.default-cargo-crates
    owner: asim
    group: asim
- name: Copy asdf-node plugin config
  ansible.builtin.copy:
    src: files/default-npm-packages
    dest: /home/asim/.default-npm-packages
    owner: asim
    group: asim
- name: asdf
  include_role:
    name: markosamuli.asdf
  vars:
    asdf_init_shell: false
    asdf_user: asim
    asdf_plugins:
#      - name: "golang"
#        versions:
#          - "1.16"
#        global: "1.16"
#      - name: "nodejs"
#        versions:
#          - "14.16.0"
#        global: "14.16.0"
      - name: "python"
        versions:
          - "anaconda3-2020.11"
        global: "anaconda3-2020.11"
      - name: "rust"
        versions:
          - "1.50.0"
        global: "1.50.0"