- name: Install packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - coreutils
      - curl
      - dirmngr
      - expect
      - fzf
      - gawk
      - git
      - gpg
      - htop
      - make
      - mc
      - tmux
      - vim
      - zsh
