- name: Install packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - expect
      - git
      - htop
      - mc
      - tmux
      - vim
      - zsh
