- name: Install rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: /home/asim/.cargo/bin/rustup
- name: Install wasm-pack
  shell: /home/asim/.cargo/bin/cargo install wasm-pack
  args:
    creates: /home/asim/.cargo/bin/wasm-pack
- name: Install twiggy
  shell: /home/asim/.cargo/bin/cargo install twiggy
  args:
    creates: /home/asim/.cargo/bin/twiggy