- name: Set up asim user
  ansible.builtin.user:
    name: asim
    group: asim
    shell: /bin/zsh
- name: Fix shell
  ansible.builtin.shell: |
    set timeout 10
    spawn chsh -sh /bin/zsh asim
    exit 0
  args:
    /usr/bin/expect
  delegate_to:
    localhost