- name: Set up asim user
  become: true
  ansible.builtin.user:
    name: asim
    group: asim
    shell: /bin/zsh

- name: Make local bin folder
  file:
    path: /home/asim/bin
    state: directory
    owner: asim
    group: asim